set(SUPPORTS_CXX "FALSE")
if("${COMPILER}" STREQUAL "intel")
  set(FC_AUTO_R8 "-r8")
  set(FFLAGS_NOOPT "-O0")
  set(CXX_LDFLAGS "-cxxlib")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
  set(FIXEDFLAGS "-fixed")
  set(SCC "icc")
  set(SFC "ifort")
  set(MPICC "mpicc")
  set(CFLAGS "-qno-opt-dynamic-align -fp-model precise -std=gnu99")
  set(MPIFC "mpif90")
  set(MPICXX "mpicxx")
  set(FREEFLAGS "-free")
  set(CXX_LINKER "FORTRAN")
  set(SCXX "icpc")
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(FC_AUTO_R8 "-fdefault-real-8")
  set(HAS_F2008_CONTIGUOUS "FALSE")
  set(FFLAGS_NOOPT "-O0")
  set(SUPPORTS_CXX "TRUE")
  set(FFLAGS "-fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
  set(FIXEDFLAGS "-ffixed-form")
  set(SCC "gcc")
  set(SFC "gfortran")
  set(MPICC "mpicc")
  set(CFLAGS "-std=gnu99")
  set(MPIFC "mpif90")
  set(MPICXX "mpicxx")
  set(FREEFLAGS "-ffree-form")
  set(CXX_LINKER "FORTRAN")
  set(SCXX "g++")
endif()
set(CPPDEFS "${CPPDEFS}  -DCESMCOUPLED")
if("${MODEL}" STREQUAL "pop")
  set(CPPDEFS "${CPPDEFS}  -D_USE_FLOW_CONTROL")
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8)")
  set(CPPDEFS "${CPPDEFS}  -DSPMD")
endif()
if("${MODEL}" STREQUAL "mom")
  set(FFLAGS "${FFLAGS}  $(FC_AUTO_R8) -Duse_LARGEFILE")
endif()
if("${COMPILER}" STREQUAL "intel")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DCPRINTEL")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -qopenmp")
    set(CFLAGS "${CFLAGS}  -qopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -O0 -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
    set(CFLAGS "${CFLAGS}  -O0 -g")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O2 -debug minimal")
    set(CFLAGS "${CFLAGS}  -O2 -debug minimal")
  endif()
  if("${MPILIB}" STREQUAL "mvapich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpich2")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpt")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "openmpi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mvapich")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "impi")
    set(SLIBS "${SLIBS}  -mkl=cluster")
  endif()
  if("${MPILIB}" STREQUAL "mpi-serial")
    set(SLIBS "${SLIBS}  -mkl")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -qopenmp")
  endif()
endif()
if("${COMPILER}" STREQUAL "gnu")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
  set(CPPDEFS "${CPPDEFS}  -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
  set(SLIBS "${SLIBS} -L$(NETCDF_FORTRAN_PATH)/lib -lnetcdff -L$(NETCDF_PATH)/lib -lnetcdf -L$(HDF5)/lib -lhdf5_hl -lhdf5 -L$(LAPACK_DIR)/lib -llapack -L$(BLASDIR) -lblas")
  if("${compile_threaded}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -fopenmp")
    set(FFLAGS "${FFLAGS}  -fopenmp")
    set(CFLAGS "${CFLAGS}  -fopenmp")
    set(CFLAGS "${CFLAGS}  -fopenmp")
  endif()
  if("${DEBUG}" STREQUAL "TRUE")
    set(FFLAGS "${FFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
    set(FFLAGS "${FFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
    set(CFLAGS "${CFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
    set(CFLAGS "${CFLAGS}  -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
  endif()
  if("${DEBUG}" STREQUAL "FALSE")
    set(FFLAGS "${FFLAGS}  -O")
    set(FFLAGS "${FFLAGS}  -O")
    set(CFLAGS "${CFLAGS}  -O")
    set(CFLAGS "${CFLAGS}  -O")
  endif()
  if("${compile_threaded}" STREQUAL "TRUE")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
    set(LDFLAGS "${LDFLAGS}  -fopenmp")
  endif()
endif()
if("${MODEL}" STREQUAL "ufsatm")
  set(INCLDIR "${INCLDIR}  -I$(EXEROOT)/atm/obj/FMS")
endif()
